# Generated by Django 4.2 on 2025-05-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название компании')),
                ('company_level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='уровень компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=150, null=True, verbose_name='улица')),
                ('build_number', models.IntegerField(blank=True, null=True, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название товара')),
                ('model', models.CharField(max_length=150, verbose_name='модель товара')),
                ('started_date', models.DateField(verbose_name='дата выхода товара на рынок')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150, verbose_name='название звена')),
                ('link_level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='уровень звена сети')),
                ('link_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='задолженность звена')),
                ('link_created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('link_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.product', verbose_name='товар сети')),
                ('link_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.company', verbose_name='поставщик звена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель звена')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
    ]
