# Generated by Django 4.2 on 2025-05-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название товара')),
                ('model', models.CharField(max_length=150, verbose_name='модель товара')),
                ('started_date', models.DateField(verbose_name='дата выхода товара на рынок')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.networklink', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
